import type { Metadata } from "next";
import "./globals.scss";
import React from "react";
import {HeaderPage} from "@/app/widgets";

export const metadata: Metadata = {
  title: "Code blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <HeaderPage/>
        {children}
      </body>
    </html>
  );
}
